### FEATURE CONFIG OPTIONS ###
# death-signs implementation is incomplete, it should always be set to false
# the others can be modified in-game

death-signs: false

death-msgs: false

brick-dropping: false

### DEATH SIGNS CONFIG ###
# Incomplete implementation, this can be ignored...?

signtext:
   zombie:
      1: 
      2: 
   skeleton:
      1:
      2:
   creeper:

### DEATH MESSAGES ###
# This will be of most interest

# &p is used to denote victim player name
# &z is used to denote killer name (name of player if it is a player, name of mob if it has one, otherwise
#    just a mob type name eg. Zombie)
# &i is used to denote an item name. This will pull from Bukkit's own list of items according to Material enum
#    or display the item's name if it was named on an anvil or otherwise given a custom name
# All other & codes are MC color codes (see: http://minecraft.gamepedia.org/Formatting_codes or search
#    "Formatting codes" on whatever the Minecraft wiki URL is)

# Message will read: "<noitem message> <item message>" if item/noitem is specified
# or: "<message>" if not.

# REMEMBER: Apostrophes need two 's in order to display.  Keep a backup of this file before you plug it in.
# A syntax error will result in this config file (in plugins folder) being wiped!

msg:
   player:
      item:
         - "wielding &i"
      noitem:
         - "&e&p&3 was slain by &e&z&3"
   
   zombie:
      item:
         - "with &i"
      noitem:
         - "&e&p &3was slain by &e&z&3&w"
         
   skeleton:
      item:
         - "with &i"
      noitem:
         - "&e&p &3was slain by &e&z&3"
         
   pigzombie:
      item:
         - "with &i"
      noitem:
         - "&e&p &3was slain by &e&z&3"
         
   arrow:
      skeleton:
         item:
            - "with &i"
         noitem:
            - "&e&p &3was shot by &e&z&3"
      player:
         item:
            - "with &i"
         noitem:
            - "&e&p &3was shot by &e&z&3"
      dispenser:
         - "&e&p &3was shot by &eHerobrine&3"
         
   fireball:
      ghast:
         - "&e&p&3 was fireballed by &e&z&3"
      blaze:
         - "&e&p&3 was fireballed by &e&z&3"
      dispenser:
         - "&e&p&3 was fireballed by &eHerobrine&3"
         
   potion:
      witch:
         item:
            - "with &i"
         noitem:
            - "&e&p&3 was killed by &e&z&3"
      player:
         item:
            - "with &i"
         noitem:
            - "&e&p&3 was turned into a newt by &e&z&3"
      dispenser:
         - "A &e&z&3 turned &e&p&3 into a newt"
      
   creeper:
      - "&e&p&3 was blown up by &e&z&3"
      
   spider:
      - "&e&p&3 was slain by &e&z&3"
      
   cavespider:
      - "&e&p&3 was slain again by &e&z&3"
   
   slime:
      - "&e&p&3 was slain by &e&z&3"
   
   wolf:
      - "&e&p&3 was slain by &e&z&3" 
   
   blaze:
      - "&e&p&3 was slain by &e&z&3"
      
   silverfish:
      - "&e&p&3 was slain by &e&z&3"
   
   endermite:
      - "&e&p&3 was slain by &e&z&3"
      
   magmacube:
      - "&e&p&3 was fried by &e&z&3"
      
   enderman:
      - "&e&p&3 was slain by &e&z&3"
      
   irongolem:
      - "&e&p&3 was slain by &e&z&3"
      
   rabbit:
      - "&e&p&3 was slain by &e&z&3"
      
   guardian:
      - "&e&p&3 was slain by &e&z&3"
      
   elderguardian:
      - "&e&p&3 was slain by &e&z&3"
      
   enderdragon:
      - "&e&p&3 was slain by &e&z&3"
      
   shulker:
      - "&e&p&3 was slain by &e&z&3"
      
   pearl:
      - "&e&p&3 overzealously pearled into the ground"
      
   tnt:
      noentity:
         - "&e&p&3 was blown up by &eTNT&3"
      entity:
         - "&e&p&3 was blown up by &eTNT&3 set off by &e&z&3"
         
   cloud:
      player:
         - "&e&p&3 was killed by &e&z&3 using magic"
      dispenser:
         - "&e&p&3 was killed by magic swirls from &e&z&3"
   
   bed:
      - "&e&p&3 was blown up by &eBed&3"
         
   fall:
      - "&e&p &3fell from a high place"
      
   cactuspoke:
      - "&e&p &3was pricked to death"
      
   lava:
      - "&e&p &3tried to swim in lava"
      
   fire:
      - "&e&p &3burned to death"
      
   wither:
      wither:
         - "&e&p &3withered away"
      explosion:
         - "&e&p &3was blown up by &e&z&3"
      kill:
         - "&e&p &3was slain by &e&z&3"
      
   suffocation:
      - "&e&p &3suffocated in a wall"
      
   drowning:
      - "&e&p &3drowned"
      
   starvation:
      - "&e&p &3starved to death"
      
   thorns:
      noitem:
         - "&e&p &3was killed trying to hurt &e&z&3"
      item:
         - "holding &i"
      
   void:
      - "&e&p &3fell into the void"
      
   magic:
      - "&e&p &3was magic'd dead by &eHerobrine&3"
      
   anvil:
      - "&e&p &3was squashed by a falling &eAnvil&3"
      
   endercrystal:
      - "&e&p&3 was blown up by &eEnder Crystal&3"
      
   feather:
      - "&e&p &3was tickled to death by &e&z&3 wielding &i"
      
   rawfish:
      - "&e&z &3scored a FISH KILL on &e&p&3 with &i"
      
   glowstone:
      - "&e&p&3 was killed by &e&z&3 with a bucket of puppies"