name: MaskOfFutures
main: com.gmail.buzziespy.MaskOfFutures.MaskOfFutures
version: 0.14.5
api-version: 1.13
softdepend: [ModMode]

commands:
   ignore-deaths:
      description: Mutes incoming death messages
      usage: /ignore-deaths
      permission:
      permission-message:
   mute-deaths:
      description: Mutes incoming death messages
      usage: /mute-deaths
      permission:
      permission-message:
   zhorse:
      description: Spawns an undead horse
      usage: /zhorse
      permission: mof.horse
      permission-message:
   shorse:
      description: Spawns an skeletal horse
      usage: /shorse
      permission: mof.horse
      permission-message:
   mof:
      description: Shows configuration options
      usage: /mof [option] [setting]
      permission: mof.change
      permission-message: "You do not have permission to use this!"
   mofmsg:
      description: View and alter custom death messages
      usage: /mofmsgs [option] [category] [message]
      permission: mof.change
      permission-message: "You do not have permission to use this!"
   wbrick:
      description: Generates a brick dropped by wither explosion
      usage: /wbrick <name>
      permission: mof.change
      permission-message: "You do not have permission to use this!"
   tame:
      description: Allows taming of untamed undead horses
      usage: /tame
      permission:
      permission-message:
   toggle-oldmsg:
      description: Toggles between custom and vanilla death messages (toggling for other players requires additional perms)
      usage: /toggle-oldmsg [player]
      permission:
      permission-message:
   oldmsg-count:
      description: Displays number of players who are seeing the vanilla death messages
      usage: /oldmsg-count
      permission: mof.change
      permission-message: "You do not have permission to use this!"
      
permissions:
   mof.*:
      description: Admin level access 
      child:
         mof.change: true
         mof.horse: true
   mof.change:
      description: Allows viewing and changing config options
      default: op
   mof.horse:
      description: Allows spawning of special horses
      default: op     
 