name: MaskOfFutures
main: com.gmail.buzziespy.MaskOfFutures.MaskOfFutures
version: 0.10.7
softdepend: [ModMode]

commands:
   zhorse:
      description: Spawns an undead horse
      usage: /zhorse
      permission: mof.horse
      permission-message:
   shorse:
      description: Spawns an skeletal horse
      usage: /shorse
      permission: mof.horse
      permission-message:
   mof:
      description: Shows configuration options
      usage: /mof [option] [setting]
      permission: mof.change
      permission-message: "You do not have permission to use this!"
   wbrick:
      description: Generates a brick dropped by wither explosion
      usage: /wbrick <name>
      permission: mof.change
      permission-message: "You do not have permission to use this!"
   tame:
      description: Allows taming of untamed undead horses
      usage: /tame
      permission:
      permission-message:
      
permissions:
   mof.*:
      description: Admin level access 
      child:
         mof.change: true
         mof.horse: true
   mof.change:
      description: Allows viewing and changing config options
      default: op
   mof.horse:
      description: Allows spawning of special horses
      default: op     
 